# Generated by Django 4.1.2 on 2022-10-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
